import sqlite3

c = sqlite3.connect("emotionplayer.db")
cr=c.cursor()

def create():
    cr.execute("CREATE TABLE if not exists song(s_id INTEGER PRIMARY KEY,s_name TEXT,s_lang TEXT,s_path TEXT )")
    cr.execute("CREATE TABLE if not exists emotion(e_id INTEGER PRIMARY KEY,e_name TEXT )")
    cr.execute("CREATE TABLE if not exists album(al_id INTEGER PRIMARY KEY,al_name TEXT )")
    cr.execute("CREATE TABLE if not exists artist(art_id INTEGER PRIMARY KEY,art_name TEXT )")
    cr.execute("CREATE TABLE if not exists songart(s_id INTEGER , art_id INTEGER )")
    cr.execute("CREATE TABLE if not exists songalb(s_id INTEGER , al_id INTEGER )")
    cr.execute("CREATE TABLE if not exists songemo(s_id INTEGER , e_id INTEGER )")
    c.commit()
    cr.close()
    c.close()

def insert_song(path,lang,name):
    cr.execute('Insert into song(s_path,s_lang,s_name) values(?,?,?)',(path,lang,name))
    c.commit()
    

def insert_emotion(name):
    cr.execute('Insert into emotion(e_name) values(?)',(name,))
    c.commit()
    

def insert_album(name):
    cr.execute('Insert into album(al_name) values(?)', (name,))
    c.commit()
    

def insert_artist(name):
    cr.execute('Insert into artist(art_name) values(?)', (name,))
    c.commit()
   

def insert_songart(s_id,art_id):
    cr.execute('Insert into songart(s_id,art_id) values(?,?)', (s_id,art_id))
    c.commit()
    
def insert_songalb(s_id,al_id):
    cr.execute('Insert into songalb(s_id,al_id) values(?,?)', (s_id,al_id))
    c.commit()
   

def insert_songemo(s_id,e_id):
    cr.execute('Insert into songemo(s_id,e_id) values(?,?)', (s_id,e_id))
    c.commit()
    

#create()
#insert_artist()
#insert_songart()
#insert_songalb()
#insert_songemo()

#################

# insert_emotion("Happy")
# insert_emotion('Chill')
# insert_emotion('Party')
# insert_emotion('Workout')
# insert_emotion('Romantic')
# insert_emotion('Drive Time')
# insert_emotion('Sad')

##################

# insert_album('Rockstar')
# insert_album('Cocktail')
# insert_album('SOTY')
# insert_album('Aashiqui 2')
# insert_album('YJHD')
# insert_album('ZNMD')
# insert_album('Vida')
# insert_album('Khaab')
# insert_album('Shape of you')
# insert_album('Purpose')
# insert_album('Ki and Ka')
# insert_album('International Villager')
# insert_album('Mi Gente')
# insert_album('Yo x Ti Tu x Mi')

#################

# insert_artist("A. R. Rahman")
# insert_artist("Abhay Deol")
# insert_artist("Akhil")
# insert_artist("Alyssa Mendonsa")
# insert_artist("Ankit Tiwari")
# insert_artist("Anupam Amod")
# insert_artist("Arijit Singh")
# insert_artist("Benny Dayal")
# insert_artist("Carlyta Mouhini")
# insert_artist("Clinton Cerejo")
# insert_artist("Dominique Cerejo")
# insert_artist("Ed Sheeran")
# insert_artist("Ehsaan Noorani")
# insert_artist("Farhan Akhtar")
# insert_artist("Gulraj Singh")
# insert_artist("Harshdeep Kaur")
# insert_artist("Hrithik Roshan")
# insert_artist("Javed Ali")
# insert_artist("Javed Bashir")
# insert_artist("Joi Barua")
# insert_artist("Justin Bieber")
# insert_artist("K. Mohan")
# insert_artist("K.K")
# insert_artist("Karthik")
# insert_artist("Kavita Seth")
# insert_artist("Loy Mendonsa")
# insert_artist("Luis Fonsi")
# insert_artist("Maria del Mar Fernández")
# insert_artist("Masuma Anwar")
# insert_artist("Miss Pooja")
# insert_artist("Mohit Chauhan")
# insert_artist("Mustafa Zahid")
# insert_artist("Nakash Aziz")
# insert_artist("Nazia Hassan")
# insert_artist("Neeraj Shridhar")
# insert_artist("Neeti Mohan")
# insert_artist("Neha Kakkar")
# insert_artist("Nikhil D'Souza")
# insert_artist("Nisha Mascarenhas")
# insert_artist("Nizami Brothers")
# insert_artist("Palak Muchhal")
# insert_artist("Rekha Bhardwaj")
# insert_artist("Sahir Ali Bagga")
# insert_artist("Salim Merchant")
# insert_artist("Shahid Mallya")
# insert_artist("Shankar Mahadevan")
# insert_artist("Shefali Alvares")
# insert_artist("Shekhar Ravjiani")
# insert_artist("Shilpa Rao")
# insert_artist("Shreya Ghoshal")
# insert_artist("Sreeram")
# insert_artist("Sunidhi Chauhan")
# insert_artist("Suraj Jagan ")
# insert_artist("Tochi Raina")
# insert_artist("Tulsi Kumar")
# insert_artist("Udit Narayan")
# insert_artist("Vishal Dadlani")
# insert_artist("Yo Yo Honey Singh")
# insert_artist("J Balvin")
# insert_artist("Rosalía")

######################

#insert_song(path,lang,name)

# insert_song(r"songs\wav\Aasan Nahin Yahan.wav","hindi","aasan nahin yahan")
# insert_song(r"songs\wav\angreji beat.wav","hindi","angreji beat")
# insert_song(r"songs\wav\Aur Ho.wav","hindi","aur ho")
# insert_song(r"songs\wav\Badtameez Dil.wav","hindi","badtameez dil")
# insert_song(r"songs\wav\Balam Pichkari.wav","hindi","balam pichkari")
# insert_song(r"songs\wav\Bhula Dena.wav","hindi","bhula dena")
# insert_song(r"songs\wav\Chahun Main Ya Naa.wav","hindi","chahu mei ya naa")
# insert_song(r"songs\wav\daaru desi.wav","hindi","daaru desi")
# insert_song(r"songs\wav\Der Lagi Lekin.wav","hindi","dar lagi lekin")
# insert_song(r"songs\wav\Despacito-ft.-Daddy-Yankee.wav","spanish","despacito")
# insert_song(r"songs\wav\Dil Dhadakne Do.wav","hindi","dil dhadakne do")
# insert_song(r"songs\wav\Dilliwaali Girlfriend.wav","hindi","dilliwaali girlfriend")
# insert_song(r"songs\wav\Ghagra.wav","hindi","ghagra")
# insert_song(r"songs\wav\Hawaa Hawaa.wav","hindi","hawaa hawaa")
# insert_song(r"songs\wav\Hum Mar Jayenge.wav","hindi","hum mar jayenge")
# insert_song(r"songs\wav\Ik Junoon (Paint It Red).wav","hindi","ik junoon")
# insert_song(r"songs\wav\Ik Junoon (Remix).wav","hindi","ik junoon remix")
# insert_song(r"songs\wav\Ilahi.wav","hindi","ilahi")
# insert_song(r"songs\wav\Ishq Wala Love.wav","hindi","ishq wala love")
# insert_song(r"songs\wav\Jo Bhi Main.wav","hindi","jo bhi main")
# insert_song(r"songs\wav\Kabira.wav","hindi","kabira")
# insert_song(r"songs\wav\Katiya Karun.wav","hindi","katiya karun")
# insert_song(r"songs\wav\Khaab.wav","punjabi","khaab")
# insert_song(r"songs\wav\Khaabon Ke Parinday.wav","hindi","khaabon ke parinday")
# insert_song(r"songs\wav\Kukkad.wav","hindi","kukkad")
# insert_song(r"songs\wav\Kun Faya Kun.wav","hindi","kun faya kun")
# insert_song(r"songs\wav\Meri Aashiqui.wav","hindi","meri aashiqui")
# insert_song(r"songs\wav\Milne Hai Mujhse Aayi.wav","hindi","Milne hai mujhse aayi")
# insert_song(r"songs\wav\Nadaan Parinde.wav","hindi","nadaan parinde")
# insert_song(r"songs\wav\Phir Se Ud Chala.wav","hindi","phir se ud chala")
# insert_song(r"songs\wav\Piya Aaye Na.wav","hindi","piya aaye na")
# insert_song(r"songs\wav\Radha.wav","hindi","radha")
# insert_song(r"songs\wav\Ratta Maar.wav","hindi","Ratta Maar")
# insert_song(r"songs\wav\Sadda Haq.wav","hindi","Sadda Haq")
# insert_song(r"songs\wav\Senorita (Remix).wav","hindi","senorita remix")
# insert_song(r"songs\wav\Senorita.wav","hindi","senorita")
# insert_song(r"songs\wav\Shape Of You.wav","english","shape of you")
# insert_song(r"songs\wav\Sheher Mein.wav","hindi","sheher mein")
# insert_song(r"songs\wav\Sooraj Ki Baahon Mein.wav","hindi","sooraj ki baahon mein")
# insert_song(r"songs\wav\Subhanallah.wav","hindi","subhanallah")
# insert_song(r"songs\wav\Sunn Raha Hai.wav","hindi","sunn raha hai")
# insert_song(r"songs\wav\Sunn Raha Hai Female.wav","hindi","sunn raha hai female version")
# insert_song(r"songs\wav\tera naam japdi phira.wav","hindi","tera naam japdi phira")
# insert_song(r"songs\wav\The Disco Song.wav","hindi","the disco song")
# insert_song(r"songs\wav\tum hi ho bandhu.wav","hindi","tum hi ho bandhu")
# insert_song(r"songs\wav\Tum hi ho.wav","hindi","tum hi ho")
# insert_song(r"songs\wav\Vele.wav","hindi","vele")
# insert_song(r"songs\wav\What Do You Mean.wav","english","what do you mean")
# insert_song(r"songs\wav\yaariyan.wav","hindi","yaariyan")
# insert_song(r"songs\wav\Dope Shope.wav","punjabi","dope shope")
# insert_song(r"songs\wav\High Heels.wav","punjabi","high heels")
# insert_song(r"songs\wav\Mi Gente.wav","spanish","mi gente")
# insert_song(r"songs\wav\Yo x Ti Tu x Mi.wav","spanish","yo x ti tu x mi")

########################

#insert_songart("1","7")
#insert_songart("2","58")
#insert_songart("3","31")
#insert_songart("4","47")
#insert_songart("5","57")
#insert_songart("6","32")
#insert_songart("7","7")
#insert_songart("7","41")
#insert_songart("8","8")
#insert_songart("8","35")
#insert_songart("9","46")
#insert_songart("10","27")
#insert_songart("11","20")
#insert_songart("11","53")
#insert_songart("12","7")
#insert_songart("12","52")
#insert_songart("13","42")
#insert_songart("13","57")
#insert_songart("14","31")
#insert_songart("15","7")
#insert_songart("15","55")
#insert_songart("16","4")
#insert_songart("16","13")
#insert_songart("16","15")
#insert_songart("16","46")
#insert_songart("16","57")
#insert_songart("17","4")
#insert_songart("17","13")
#insert_songart("17","15")
#insert_songart("17","46")
#insert_songart("17","57")
#insert_songart("18","7")
#insert_songart("18","31")
#insert_songart("19","36")
#insert_songart("19","44")
#insert_songart("19","48")
#insert_songart("20","31")
#insert_songart("21","7")
#insert_songart("21","16")
#insert_songart("21","42")
#insert_songart("21","54")
#insert_songart("22","16")
#insert_songart("23","3")
#insert_songart("24","4")
#insert_songart("24","31")
#insert_songart("25","39")
#insert_songart("25","45")
#insert_songart("26","1")
#insert_songart("26","18")
#insert_songart("26","40")
#insert_songart("27","7")
#insert_songart("27","41")
#insert_songart("28","7")
#insert_songart("29","1")
#insert_songart("29","31")
#insert_songart("30","31")
#insert_songart("31","23")
#insert_songart("31","55")
#insert_songart("32","48")
#insert_songart("32","50")
#insert_songart("32","56")
#insert_songart("32","57")
#insert_songart("33","47")
#insert_songart("33","57")
#insert_songart("34","31")
#insert_songart("35","2")
#insert_songart("35","14")
#insert_songart("35","17")
#insert_songart("35","28")
#insert_songart("36","2")
#insert_songart("36","9")
#insert_songart("36","14")
#insert_songart("36","17")
#insert_songart("36","28")
#insert_songart("37","12")
#insert_songart("38","24")
#insert_songart("38","31")
#insert_songart("39","10")
#insert_songart("39","11")
#insert_songart("39","26")
#insert_songart("40","51")
#insert_songart("41","5")
#insert_songart("42","50")
#insert_songart("43","19")
#insert_songart("43","38")
#insert_songart("43","47")
#insert_songart("44","8")
#insert_songart("44","34")
#insert_songart("44","52")
#insert_songart("45","25")
#insert_songart("45","35")
#insert_songart("46","7")
#insert_songart("47","21")
#insert_songart("47","48")
#insert_songart("47","57")
#insert_songart("48","22")
#insert_songart("48","49")
#insert_songart("49","22")
#insert_songart("49","49")
#insert_songart("50","58")
#insert_songart("51","58")
#insert_songart("52","59")
#insert_songart("53","60")

########################

# insert_songalb("1","4")
# insert_songalb("2","2")
# insert_songalb("3","1")
# insert_songalb("4","5")
# insert_songalb("5","5")
# insert_songalb("6","4")
# insert_songalb("7","4")
# insert_songalb("8","2")
# insert_songalb("9","6")
# insert_songalb("10","7")
# insert_songalb("11","6")
# insert_songalb("12","5")
# insert_songalb("13","5")
# insert_songalb("14","1")
# insert_songalb("15","4")
# insert_songalb("16","6")
# insert_songalb("17","6")
# insert_songalb("18","5")
# insert_songalb("19","3")
# insert_songalb("20","1")
# insert_songalb("21","6")
# insert_songalb("22","1")
# insert_songalb("23","8")
# insert_songalb("24","6")
# insert_songalb("25","3")
# insert_songalb("26","1")
# insert_songalb("27","4")
# insert_songalb("28","4")
# insert_songalb("29","1")
# insert_songalb("30","1")
# insert_songalb("31","4")
# insert_songalb("32","3")
# insert_songalb("33","3")
# insert_songalb("34","1")
# insert_songalb("35","6")
# insert_songalb("36","6")
# insert_songalb("37","9")
# insert_songalb("38","1")
# insert_songalb("39","6")
# insert_songalb("40","5")
# insert_songalb("41","4")
# insert_songalb("42","4")
# insert_songalb("43","2")
# insert_songalb("44","3")
# insert_songalb("45","2")
# insert_songalb("46","4")
# insert_songalb("47","3")
# insert_songalb("48","10")
# insert_songalb("49","2")
# insert_songalb("50","11")
# insert_songalb("51","12")
# insert_songalb("52","13")
# insert_songalb("53","14")

########################

# insert_songemo("1","5")
# insert_songemo("1","6")
# insert_songemo("1","7")
# insert_songemo("2","3")
# insert_songemo("2","4")
# insert_songemo("3","2")
# insert_songemo("3","7")
# insert_songemo("4","1")
# insert_songemo("4","2")
# insert_songemo("4","3")
# insert_songemo("4","6")
# insert_songemo("5","1")
# insert_songemo("5","2")
# insert_songemo("5","3")
# insert_songemo("5","5")
# insert_songemo("6","5")
# insert_songemo("6","7")
# insert_songemo("7","5")
# insert_songemo("7","6")
# insert_songemo("7","7")
# insert_songemo("8","1")
# insert_songemo("8","2")
# insert_songemo("8","3")
# insert_songemo("8","4")
# insert_songemo("9","5")
# insert_songemo("9","6")
# insert_songemo("9","7")
# insert_songemo("10","5")
# insert_songemo("11","1")
# insert_songemo("11","3")
# insert_songemo("11","4")
# insert_songemo("11","6")
# insert_songemo("12","1")
# insert_songemo("12","2")
# insert_songemo("12","3")
# insert_songemo("12","5")
# insert_songemo("13","1")
# insert_songemo("13","2")
# insert_songemo("13","3")
# insert_songemo("13","4")
# insert_songemo("13","5")
# insert_songemo("14","1")
# insert_songemo("14","3")
# insert_songemo("14","6")
# insert_songemo("15","5")
# insert_songemo("15","7")
# insert_songemo("16","1")
# insert_songemo("16","2")
# insert_songemo("16","4")
# insert_songemo("16","6")
# insert_songemo("17","1")
# insert_songemo("17","2")
# insert_songemo("17","4")
# insert_songemo("17","6")
# insert_songemo("18","1")
# insert_songemo("18","2")
# insert_songemo("18","3")
# insert_songemo("18","5")
# insert_songemo("19","5")
# insert_songemo("19","6")
# insert_songemo("20","6")
# insert_songemo("20","7")
# insert_songemo("21","5")
# insert_songemo("21","6")
# insert_songemo("21","7")
# insert_songemo("22","1")
# insert_songemo("22","3")
# insert_songemo("23","1")
# insert_songemo("23","2")
# insert_songemo("23","5")
# insert_songemo("24","4")
# insert_songemo("24","6")
# insert_songemo("25","1")
# insert_songemo("25","3")
# insert_songemo("25","4")
# insert_songemo("26","7")
# insert_songemo("27","5")
# insert_songemo("27","7")
# insert_songemo("28","3")
# insert_songemo("28","5")
# insert_songemo("28","6")
# insert_songemo("28","7")
# insert_songemo("29","3")
# insert_songemo("29","4")
# insert_songemo("30","2")
# insert_songemo("30","6")
# insert_songemo("30","7")
# insert_songemo("31","5")
# insert_songemo("31","6")
# insert_songemo("31","7")
# insert_songemo("32","1")
# insert_songemo("32","3")
# insert_songemo("32","5")
# insert_songemo("32","6")
# insert_songemo("33","1")
# insert_songemo("33","3")
# insert_songemo("33","4")
# insert_songemo("33","6")
# insert_songemo("34","4")
# insert_songemo("35","1")
# insert_songemo("35","2")
# insert_songemo("35","3")
# insert_songemo("36","1")
# insert_songemo("36","2")
# insert_songemo("36","3")
# insert_songemo("37","4")
# insert_songemo("37","5")
# insert_songemo("38","1")
# insert_songemo("38","2")
# insert_songemo("38","6")
# insert_songemo("39","1")
# insert_songemo("39","6")
# insert_songemo("40","5")
# insert_songemo("40","6")
# insert_songemo("41","2")
# insert_songemo("41","5")
# insert_songemo("41","6")
# insert_songemo("41","7")
# insert_songemo("42","5")
# insert_songemo("42","6")
# insert_songemo("42","7")
# insert_songemo("43","1")
# insert_songemo("43","2")
# insert_songemo("43","3")
# insert_songemo("43","4")
# insert_songemo("44","1")
# insert_songemo("44","2")
# insert_songemo("44","3")
# insert_songemo("44","4")
# insert_songemo("44","5")
# insert_songemo("44","6")
# insert_songemo("45","1")
# insert_songemo("45","3")
# insert_songemo("46","5")
# insert_songemo("46","7")
# insert_songemo("47","1")
# insert_songemo("47","3")
# insert_songemo("47","4")
# insert_songemo("47","6")
# insert_songemo("48","2")
# insert_songemo("49","2")
# insert_songemo("49","6")
# insert_songemo("49","7")
# insert_songemo("50","1")
# insert_songemo("50","2")
# insert_songemo("50","3")
# insert_songemo("50","6")
# insert_songemo("51","1")
# insert_songemo("51","2")
# insert_songemo("51","3")
# insert_songemo("51","6")
# insert_songemo("52","1")
# insert_songemo("52","2")
# insert_songemo("52","3")
# insert_songemo("52","6")
# insert_songemo("53","1")
# insert_songemo("53","2")
# insert_songemo("53","3")
# insert_songemo("53","6")

###############
